cloud:
  aws:
    credentials:
      access-key: YOUR_ACCESS_KEY
      secret-key: YOUR_SECRET_KEY
    region:
      static: YOUR_REGION
    stack:
      auto: false
    s3:
      bucket: YOUR_BUCKET_NAME

spring:
  datasource:
    url: YOUR_DATABASE_URL
    username: YOUR_DATABASE_USERNAME
    password: YOUR_DATABASE_PASSWORD
    driverClassName: com.mysql.cj.jdbc.Driver
